### ISSUE TITLE
fixup! and squash! docs do not reflect actual behavior

### ISSUE THREAD

**Issue by Narretz** [jzaefferer/commitplease#102]
The docs say: 

> The following ways to begin a commit message are special and always valid:
> ...
> fixup! or squash! which are generated by git commit --fixup and --squash

But in fact, with style: angular, a single `fixup!` on the first line is also valid.

The docs say that only fixup! and squash! which include the line of the commit to fixup / squash are valid.

**Comment by jzaefferer** [comment]
I'm not sure I understand the issue here. Could you add an example or two with valid and invalid samples, both expected and actual? We could also use those for adding more unit tests.

**Comment by Narretz** [comment]
Sure!
`git commit --fixup <committish>` creates a commit message that looks like:

```
fixup! fix(scope): whatever the first line in this commit message is

Message body here ...
```

But commitplease also allows a commit message that looks like this:

```
fixup!

Message body here ...
```

The docs say only the first version is allowed.

**Comment by jzaefferer** [comment]
Gotcha. So we could validate that there's some text following the `fixup!` prefix. Checking if its the subject line of another commit is going to be quite a bit more effort, and I'm not sure if that's worth it. Personally I use `fixup!` a lot with just some text following the prefix.

Maybe a change in the docs is enough here?

**Comment by Narretz** [comment]
A change in the docs is okay with me, less confusing definitely

Jörn Zaefferer <notifications@github.com> schrieb am Fr., 14. Juli 2017
10:40:
