### ISSUE TITLE
scope required when it should be optional

### ISSUE THREAD

**Issue by FezVrasta** [jzaefferer/commitplease#104]
according to the Angular guidelines, the scope is optional. But commitplease seems to complain about it missing in my commit messages.

Is there some config I need to set or is it  abug?

**Comment by all3fox** [comment]
Hey @FezVrasta, no, there is no config. I remember reading https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit and seeing the line:

```
<type>(<scope>): <subject>
```

I wondered, if the `()` should be left empty if there is no scope. Then I grepped the contents of the `git log` and did not find any examples of messages with no scope. So I decided that the parenthesis stay in.

If you feel like it is a bad decision, take a look at `lib/styles/angular.js`, that rather small script has all the logic for angular coded-in. If you end up doing adjustments that suit  you better, please submit a PR!

**Comment by FezVrasta** [comment]
![image](https://user-images.githubusercontent.com/5382443/30222256-e6059864-94c6-11e7-8705-96073f4a4fbb.png)

**Comment by all3fox** [comment]
Which in my mind should translate into:

```
<type><(scope)>: <subject>
```

**Comment by FezVrasta** [comment]
So, for you optional means mandatory? That's weird. Anyway, I switched to `validate-commit-msg`, it works better, thanks anyway.
