### ISSUE TITLE
Check register after the colon

### ISSUE THREAD

**Issue by markelog** [jzaefferer/commitplease#32]
http://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines has an example - 

> Component: Short Description

I wonder if we should check for register of the first word, in this case, "Short"?

Should it be in upper-case though? Linguistically speaking, it should be a lower-case letter.

**Comment by jzaefferer** [comment]
Do you mean "case" (or is it casing?). "register" doesn't make sense to me in this context. Assuming this is about upper/lower-casing: I think both variants are valid. If the guidelines were to require something, I'd be more inclined to implement something here. Personally I think that's not worth it.

**Comment by markelog** [comment]
Okay, as i suspect, that's my case of nit-picking then

**Comment by jzaefferer** [comment]
Alright. Btw. thank you for introducing the `-v` (aka `--verbose`) option to me, I'm now using that all the time.
