### ISSUE TITLE
Prohibit use of `#NNNN` ticket references

### ISSUE THREAD

**Issue by dmethvin** [jzaefferer/commitplease#33]
Since several projects use `#` to indicate non-Github bug trackers, it would be handy to have the commit checker look for those references and abort the commit if they're found. This should be a non-default option since most Github projects do use `#` to refer to tickets and PRs.

Ref https://github.com/jquery/contribute.jquery.org/issues/102

**Comment by dmethvin** [comment]
Seems like we'll need a new option @jzaefferer, what's your preference on that logic? I was thinking about `disallowHash` as the name so falsy would be the default.

**Comment by jzaefferer** [comment]
Maybe make it a bit more generic? Like `ticketPrefixes` (or something along those lines), with a default of "#|gh-", so that its still valid JSON and will always be compiled as a RegEx with "^" and "$" around it. Then you can override it with any kind of prefixes that you like.

**Comment by dmethvin** [comment]
Oh i like that better.

**Comment by all3fox** [comment]
It is possile to prohibit `#NNNN` style ticket references by setting the `ticketPattern` and `markerPattern` regular expressions, shown in [this PR](https://github.com/jquery/jquery/pull/3176) and by [this profile in test.js](https://github.com/jzaefferer/commitplease/blob/058dd65c8bc5b0a5946d7a15c7f54b99eb730554/test.js#L9)

**Comment by jzaefferer** [comment]
PS: Those options are recent additions, so it is **now** possible.
