### ISSUE TITLE
Validate use of `Ref` ticket references

### ISSUE THREAD

**Issue by dmethvin** [jzaefferer/commitplease#34]
The [jQuery ticket reference guidelines](http://contribute.jquery.org/commits-and-pull-requests/#references) allow the use of `Ref` to reference a ticket without closing it. These should be validated as well, since it will impact the efficacy of #33. 

I used #33 there instead of gh-33 on purpose. :smiling_imp:

**Comment by jzaefferer** [comment]
Sounds reasonable. I'm currently heavily focused on finishing jQuery UI 1.12. Maybe someone from the Core team can help this and #33? [Add a test](https://github.com/jzaefferer/commitplease/blob/master/test.js), implement it in [lib/validate.js](https://github.com/jzaefferer/commitplease/blob/master/lib/validate.js). I can find a few minutes for reviewing PRs, tagging and publishing, but the implementation would have to wait a while.

**Comment by dmethvin** [comment]
I created this ticket because I was looking at it, just didn't want to assign it to myself in case I got sidetracked.

**Comment by jzaefferer** [comment]
:+1:

**Comment by arschmitz** [comment]
I actually disagree with this you don't always want to just ref a ticket what if you want to reference a blog post or some other reason for the change i think ref still makes sense in this case.

You can also use this to reference issues from other currently unsupported issue trackers like Jira

**Comment by dmethvin** [comment]
I'd be fine with all these using the `ticketPrefixes` @jzaefferer proposed in #33 and one of the prefixes could be `http` to allow arbitrary links. Would that work for you @arschmitz?

**Comment by arschmitz** [comment]
@dmethvin that would work for my use case since my PR to support jira landed however ref could still be useful for other as of yet unsupported issue tracker. I don't really care any more though since Jira is now supported.

**Comment by jzaefferer** [comment]
I've reviewed this with @all3fox. We can't think of any usecase where commitplease could correctly point out an issue with a `Ref` line. If someone wants to include `Ref undisclosed security bug CVE123`, we should let them. Since this line isn't used to close tickets or generate changelogs, it seems like there's nothing to win here.

We can reopen with good usecases.

**Comment by arschmitz** [comment]
👍
