### ISSUE TITLE
Feature request: Auto modify the message based on rules

### ISSUE THREAD

**Issue by stevemao** [jzaefferer/commitplease#38]
Eg: Auto capitalise the first letter of the Component and Short Description
Remove the dot at the end of the Component and Short Description
Fix some common typos?
Remove empty lines?

What do you think?

**Comment by jzaefferer** [comment]
Considering the current implementation, which uses git's commit-msg hook, this is somewhere between hard to impossible to implement. I'd have no idea where to start. That said, if you can come up with something, I'd review it.

**Comment by jzaefferer** [comment]
Closing this due to lack of interest and difficulty of implementing it.
