### ISSUE TITLE
Feature request: Customised rule

### ISSUE THREAD

**Issue by stevemao** [jzaefferer/commitplease#39]
jQuery uses

```
Component: Short Description
```

User should be able to configure it so that something like

```
Short Description: Component
```

can be also validated. 

IMO this is not too different from the current implementation so it should be easy. I can put together a PR.

If you agree this is a good idea repos like
https://github.com/jshint/jshint/commits/master
https://github.com/angular/angular.js/commits/master
can use this module.

**Comment by jzaefferer** [comment]
Changes to the validator should be pretty straight-forward. Would be good to only add features that are going to be used somewhere. With that in mind, a PR is welcome.

**Comment by jzaefferer** [comment]
Angular uses a different format, which we're implementing in https://github.com/jzaefferer/commitplease/pull/53

JShint seems to have switched to ad `[[<type>]] <subject>` format, where `<type>` is similar to the one used by Angular. I wonder if we the new options would allow this configuration.

**Comment by jzaefferer** [comment]
Looking at the original suggestion, there's not much to do here. I'm going to open a separate issue to do some scanning of popular open source projects, to identify other popular styles.
