### ISSUE TITLE
Cant use the word fixed even as part of a component name

### ISSUE THREAD

**Issue by arschmitz** [jzaefferer/commitplease#40]
jQuery Mobile has a fixedToolbar component but the message FixedToolbar: ..... fails because fixed is not followed by a ticket ref.

**Comment by jzaefferer** [comment]
This applies to all lines: https://github.com/jzaefferer/commitplease/blob/master/lib/validate.js#L62

Could change that to only looks at lines beyond the first. Since the first has plenty other checks, that should work just fine. Would that work for you?

**Comment by arschmitz** [comment]
That would work for this case. Another more general option would would be to check that the key word is followed by a space. If it is not it must be part of a compound word or name and therefor should not be caught by validation.

**Comment by jzaefferer** [comment]
@gabrielschulhof would you put together a PR for that? Patching validate.js is pretty simple, just extend the unit tests and and some rule of `lib/validate.js`.

**Comment by arschmitz** [comment]
@jzaefferer i'm assuming you mean me in which case i would be happy to :-)
