### ISSUE TITLE
Support for Angular commit message style guides

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/commitplease#43]
I'd like to see more adoption of this project. For that it should have presents and options to support more commit message style guides. The one I'm aware of is the [angular style guide for commit message](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit). There are probably more.

I hope more people are interested in extending this project to support the style of commit messages. I've already solved the git commit-msg hook integration.

**Comment by jzaefferer** [comment]
@mzgol can I interest you in championing support for the angular style guide? Did you get a chance to talk about this with anyone in the angular community?

**Comment by sherlcode13** [comment]
@jzaefferer  I want to work on this issue .

**Comment by jzaefferer** [comment]
You're welcome! I suggest you check out the existing validation along with the Angular style guide, then come back here and we can discuss the next steps.

**Comment by all3fox** [comment]
@jzaefferer @sherlcode13 here are my thoughts about commit style guides for [Angular](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit) and [jQuery](https://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines):

The similarities:
-----------

1. Both separate the commit message into three parts: header, body and footer (Angular) and Subject, Long Description and References (jQuery). The first part is obligatory, the rest are optional.
2. Both have implemention details and corner-cases that differ :P

The differences:
-----------

1. `commitplease` is an npm package. It is added into a `package.json` of a project and then `npm install`'ed. It automatically creates the `commit-msg` in `.git/hooks` (ready out-of-the-box). On the other hand, the [validate-commit-msg.js][1] is *a script* that is ready to be symlinked from `.git/hooks`, which should be done sort of manually (in case of Angular, by the [init-repo.sh][2])
2. Angular's `validate-commit-msg.js` is [basically a regex][3] which, [by the looks of it][6], is applied *only to the first line* of the commit message (provided that it should not be ignored and is not longer than a certain number of characters). The [/lib/validate.js][4] from `commitplease` is a couple of smaller (but not always) regexes which are applied line-by-line of the commit  message.

Random thoughts:
------
- If you checkout jQuery and run `npm install`, `commitplease` does get installed but there is no mention of it inside the entire `.git/hooks`. Instead, the `commit-msg` hook is some funny shell script (aborted trying to understand it). However, on my toy project `npm install`'ing `commitplease` does create a `commit-msg` hook. ([the last couple of commits here](https://github.com/all3fox/algos-js/commits/master) show that it installed for me).
- `commitplease` did not remove its git hook when I `npm uninstall`'ed it from my toy project (is that a bug?)

Conclusion:
---

Basically, I am very interested in doing this GSoC project, so let me know if you are. The things that attract me here: I have a rough idea of what has to be done and how. The success criteria is also clear (get adopted by jQuery and Angular, at least as an optional commit check). If it helps, I also did [two small contributions][5] to jQuery Core.

[1]: https://github.com/angular/angular.js/blob/36831eccd1da37c089f2141a2c073a6db69f3e1d/validate-commit-msg.js

[2]: https://github.com/angular/angular.js/blob/59bfe8e5a9edf7ba000d258b9ac1ef8355c9aca7/init-repo.sh

[3]: https://github.com/angular/angular.js/blob/36831eccd1da37c089f2141a2c073a6db69f3e1d/validate-commit-msg.js#L19

[4]: https://github.com/jzaefferer/commitplease/blob/7d12f472ae0f69197086de731d4c2bfcb637fa1b/lib/validate.js

[5]: https://github.com/jquery/jquery/commits/master?author=all3fox

[6]: https://github.com/angular/angular.js/blob/36831eccd1da37c089f2141a2c073a6db69f3e1d/validate-commit-msg.js#L98-L99

**Comment by jzaefferer** [comment]
@all3fox that looks great! Before you do anything else, please apply on the official GSoC website, where you can attach your Google Doc as well.

After that: I suggest you integrate your analysis (the one posted above) into your proposal, as part of the "detailed description" section, before the timeline.

As for your analysis: I don't know why the hook isn't installed for jQuery Core. It might be related to the "husky" dependency; I don't know what its supposed to do, maybe https://github.com/jquery/jquery/issues/2915 helps.

There are other jQuery Foundation projects that use commitplease, like [jQuery UI](https://github.com/jquery/jquery-ui/blob/c41b8809663ea96f78e01f35fdf565d26a9800f5/package.json#L55) or [QUnit](https://github.com/jquery/qunit/blob/ab4a048e2cf0c59fab1e80093d26fe6464d411fe/package.json#L54-L66). Those projects shouldn't have a problem updating to newer versions. Another sample is Globalize, [which doesn't use the commit hook](https://github.com/jquery/globalize/blob/ab675203d8784c641c432e3cb10dfce564d80e7a/package.json#L91-L93), but integrates the validation through a grunt plugin.

On the risks side, if absolutely none of the Angular projects can be convinced to at least give it a try: The commercial/not-open-source project I'm currently spending most of my time on is using the Angular commit message style guide, so I could use my colleagues as beta testers.

As for code contributions: Getting commits landed in jQuery Core is a nice accomplishment, even if its "just" tests. But then commitplease isn't related to the DOM at all, so this fits nicely.

I very much like the idea of integrating Angular's validation script and its tests into commitplease. The tests should be a great starting point for implementing their commit message style.

**Comment by all3fox** [comment]
@jzaefferer thanks! I have included my previous comment into the proposal.

> Before you do anything else, please apply on the official GSoC website, where you can attach your Google Doc as well.

Actually, this google doc is the result of my activity on the GSoC website. I crossposted the link to it in my previous message for convenience. The website tells me that my draft proposal should be already visible to the organisation. I understand that my application is not yet complete because I have not "submitted my final proposal" in the `pdf` form. I was planning on doing that on about the 25th after your feedback. Do tell me if you need/would like me to submit the final proposal earlier.

**Comment by jzaefferer** [comment]
Sorry, nevermind that, I just missed your entry in the list. That's all good. The rest is still valid though :-)

**Comment by jzaefferer** [comment]
@all3fox The deadline is pretty close. Please submit your PDF proposal ("complete" your application) as soon as possible.

**Comment by dmethvin** [comment]
If it helps you, I was messing with fixes for #33 and #34 trying to take the regexps out of the code and make them part of the config. It seemed to take at least 3 regexps and documenting exactly what they did was tricky. Here's that work, unfinished: https://github.com/dmethvin/commitplease/commit/8c5dc99d74fcdb823d23a7ffd1dda7bf3eba515b

**Comment by jzaefferer** [comment]
Fixed by https://github.com/jzaefferer/commitplease/commit/344353cab7b051a2b1188703cf12944f73fd8b9a released as [2.5.0](https://github.com/jzaefferer/commitplease/releases/tag/v2.5.0)
