### ISSUE TITLE
decouple validation API from git-hook runner

### ISSUE THREAD

**Issue by kilianc** [jzaefferer/commitplease#48]
Since I usually use `husky` or `shared-git-hooks` already, it would be cool if `commitplease` was a binary or simple a lib that I can call from my own script.

**Comment by jzaefferer** [comment]
There's currently a clutch for this, setting `nohook: true` in package.json: https://github.com/jzaefferer/commitplease#customizing-the-bundled-options

Besides that, the only other solution I can think of would be to extract the validation into a separate module, then use that module here, or anywhere else where there's also a commit-msg hook in place. I'd prefer keeping both in one module though. Any ideas?

PS: Is your setup in a public repo? I'm interested in seeing how this module is used.

**Comment by kilianc** [comment]
I was just playing with it, I copy pasted the snippet in the readme into an executable node script...

In general a lot of git related modules on npm embed their own hook runner - installer, instead of just releasing a bin, which is a bummer.

`nohook: true` seems like what I need!
