### ISSUE TITLE
Use ES2015

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/commitplease#55]
Use babel or [bublé](http://buble.surge.sh/) (along with rollup?) to allow using ES2015 for development, but publish ES5 code to npm.

**Comment by all3fox** [comment]
We have decided to go with bublé together with rollup. Here is my current understanding of this:

1. rollup needs ES6 style `import / export` machinery, I will be switching to that.
2. rollup needs an "entry point", i.e. a file it will take and unroll all its dependencies. There are a couple of problems here: 
  1. It is my understanding that the entry point for commitplease is `commit-msg-hook.js` but rollup does not like that it starts with a shebang. I will look into that. Doing rollup on `index.js` works.
  2. The npm module actually has to have more than one file in it: `commit-msg-hook.js` along with `install.js` and `uninstall.js`, right? So, if we want to rollup `install.js` and `uninstall.js` as well, it looks to me like rollup will have to be called more than once (i.e. three times) somewhere like the `prepublish` script of the `package.json`?
3. After rollup is done, bublé should run and transpile ES6 to ES5, I have not reached this point yet.

There is also a "Getting started with plugins" section [on the rollup website](http://rollupjs.org/guide/#getting-started-with-plugins). It shows how to use rollup with Babel (not bublé). Maybe this "plugin" approach is nicer than manualy running bublé after rollup inside some script section of `package.json`. An example for this approach is [this pull request](https://github.com/rollup/rollup/pull/620/files).

**Comment by jzaefferer** [comment]
Thanks for the analysis so far. Currently I'm thinking this might not be such a good idea after all, since at least the switch to ES6 module syntax is probably introducing more complexity than its worth.

I suggest we put this on hold for now, and instead check what minimal node version we should support (look for some usage numbers). Then check what ES6 features we can use natively (without requiring a transpiler) in that version. I find destructuring assignments, template strings and some other shorthands to be pretty useful.

**Comment by Arkni** [comment]
> I suggest we put this on hold for now, and instead check what minimal node version we should support (look for some usage numbers). Then check what ES6 features we can use natively (without requiring a transpiler) in that version. I find destructuring assignments, template strings and some other shorthands to be pretty useful.

http://node.green/

**Comment by jzaefferer** [comment]
Nice, thanks @Arkni. Looks like we'd need at least 4.4.x to be able to use, for example, template literals. Currently we're still [testing against 0.12, 4 and stable](https://github.com/jzaefferer/commitplease/blob/master/.travis.yml#L4-L6).

Would still be good to have some usage numbers.

**Comment by Arkni** [comment]
This [PDF from`nodesource`](https://nodesource.com/assets/blog/node-by-numbers/node-by-numbers.pdf) includes statistics of `NodeJS` usage (download, ...) in 2015. Maybe it can be of help to you.

**Links**:
* Blog post: https://nodesource.com/blog/node-by-numbers-2015/
* PDF: https://nodesource.com/assets/blog/node-by-numbers/node-by-numbers.pdf

**Comment by jzaefferer** [comment]
I'm closing this for now. Maybe revisit later this year, when adoption of newer node versions improved significantly.
