### ISSUE TITLE
On-demand validation

### ISSUE THREAD

**Issue by jzaefferer** [jzaefferer/commitplease#70]
I know that @rxaviers doesn't much like the commit-msg hook, instead prefers validation as part of `npm test` (locally or via CI). For Globalize, he's set up a combination of `nohook: true` and a grunt plugin that validates a certain range of commits: https://github.com/jquery/globalize/blob/master/package.json#L76

The issues with that approach: You need the extra code to run the validation on-demand - this could be built into commitplease instead. And adding `nohook: true` to package.json makes this a project-wide setting. It would be better to be able to override this per install, so he could create `.npmrc` with `[...]commitplease.nohook:true`, while everyone else on the project uses the hook.

That would also be a decent answer for parts of #67

**Comment by all3fox** [comment]
I have taken a closer look at [grunt-commitplease](https://github.com/rxaviers/grunt-commitplease/)

Currently, our `commit-msg` hook uses the fact that it is either in `node_module/commitplease` or `.git/hooks` directory, so it can just go two levels up and get the `.git/COMMIT_EDITMSG` file. So, it can be run standalone with `node node_modules/commitplease`, like we do for jQuery Core. That will check the latest `.git/COMMIT_EDITMSG` (only the latest one) or fail if project history is empty.

So, I think here is what should happen. The instance of `commit-msg-hook.js` that gets copied to `.git/hooks` needs to get extra "check .npmrc for nohook" logic. The other instance that stays inside `node_modules` should get extra "let the user select a larger range of commits" logic (like in grunt-commitplease).

Tell me what you think, I am a bit confused how to do that at the moment.

**Comment by all3fox** [comment]
I'd say `2.7.x` solves both the "validating commit range" and "better using .npmrc/package.json to skip hook"
