### ISSUE TITLE
Error on rebase

### ISSUE THREAD

**Issue by flore77** [jzaefferer/commitplease#75]
I have received this error:

![image](https://cloud.githubusercontent.com/assets/11819686/17442712/ecbcb610-5b2e-11e6-9811-3f65c9ccfb9f.png)

The context was:
- squashing something like 16 commits
- squash only the latests 15
- the last one rewarding

Git opens vim to modify the message for the rewarding commit, I modified message, I think it was a correct commit message and then commitplease crashed with the above error. After that I continued the rebase and everything went well.

**Comment by all3fox** [comment]
Hi @flore77, could you please tell me your version of commitplease? Interactive rebase squashing latest 4 commits (with squashing 3 and rewording the latest one) worked for me on `2.6.1`

**Comment by flore77** [comment]
@all3fox  Sorry, not the lastest one is rewarding, the oldest commit is rewarded, like this:

![image](https://cloud.githubusercontent.com/assets/11819686/17455612/458459a2-5bb5-11e6-85d0-c79e297b1c3c.png)

generates the error.

I am using the 2.6.1 version.

**Comment by all3fox** [comment]
@flore77 here is my take, it went without problem:

![screenshot from 2016-08-06 18-48-56](https://cloud.githubusercontent.com/assets/962850/17457661/39517796-5c0f-11e6-9163-4f8b1d3449ed.png)

My current guess is: you updated to a newer version of commitplease but left an commit-msg hook from an older version. Could you please try to reinstall and manually delete the hook like so:

```
npm uninstall commitplease
rm .git/hooks/commit-msg
npm install commitplease
```

**Comment by flore77** [comment]
@all3fox I manually delete the hook and now it's working.
