### ISSUE TITLE
fs.existsSync followed by fs.mkdirSync fail with EEXIST

### ISSUE THREAD

**Issue by all3fox** [jzaefferer/commitplease#76]
There is [a problem][1] with angular continuous integration. My suspicion is that the repository is created in between the calls to `fs.existsSync` and `fs.mkdirSync`, leading to failure. So, I am fixing our `install.js` script to "ask forgiveness not permission" like so:

```
function xmkdirSync (path, mode) {
  try {
    fs.mkdirSync(path, mode)
  } catch (err) {
    if (/EPERM/.test(err.message)) {
      console.error('Failed to create: ' + git)
      console.error('Make sure you have the necessary permissions')
    } else if (/EEXIST/.test(err.message)) {
      // do nothing
    } else {
      throw err
    }
  }
}
```

Is that ok? Is there perhaps some other issue I am missing?

[1]: https://circleci.com/gh/angular/angular/3788

**Comment by jzaefferer** [comment]
Since `existsSync` and `exists` are both deprecated, it makes sense to apply this patch. To test for permission, we could call `fs.access` though: https://nodejs.org/api/fs.html#fs_fs_exists_path_callback

**Comment by jzaefferer** [comment]
Also:
> fs.exists() should not be used to check if a file exists before calling fs.open(). Doing so introduces a race condition since other processes may change the file's state between the two calls. Instead, user code should call fs.open() directly and handle the error raised if the file is non-existent.

**Comment by jzaefferer** [comment]
Somewhat related, why are we checking for existence of `.git`, creating it if it doesn't exist? That seems wrong.

**Comment by all3fox** [comment]
> Somewhat related, why are we checking for existence of .git, creating it if it doesn't exist? That seems wrong.

My initial problem was that we aborted install if we were not inside a `.git` repository, which broke global install. I also suspected that it broke `npm install` if `commitplease` was included as an ordinary `dependency` rather than a `devDependency` of some other module (not sure though). So I decided just to create `.git/hooks` all the time.

**Comment by jzaefferer** [comment]
How about not installing the hook if `.git` doesn't exist?

**Comment by all3fox** [comment]
> How about not installing the hook if .git doesn't exist?

That sounds good but looks like it wont help with the Angular's race condition. There, it looks like:
 1. `fs.existsSync(git)` reports no `.git`
 1. Something creates `.git`
 1. Commitplease fails when creating `.git`

If we do not install the hook if `.git` is missing, then:
 1. `fs.existsSync(git)` reports no `.git`
 1. Skip installing the hook
 1. Something creates `.git`
And we did not install properly.

So, I need to better understand the exact reason of that race condition. Then I will know if "not installing the hook if .git doesn't exist" is a good idea.

**Comment by jzaefferer** [comment]
Its pretty strange that `npm-install` would run while `.git` doesn't yet exist. How does it know what to install when the git repo isn't properly cloned?

**Comment by all3fox** [comment]
I was thinking about how I could reproduce that. So, I signed up on CircleCI and got my commitplease branch to angular to fail. Now comes the question of how to install a development version of commitplease to CircleCI.

So I fiddled with a toy project just to figure out how npm publishing mechanics works. And then I found a really [good blogpost][1]. You can "prepublish" your module with:

```
npm version prepatch # or preminor or premajor
npm publish --tag future # any tag apart from latest
```
That will put a `2.7.1-0` version of commitplease onto npm but nobody, except those who request that version explicitly, will get it downloaded with `npm install commitplease`

Could we do that prepublish to debug the race condition? Otherwise I do not know how to reproduce.

[1]: https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420#.jx2xvzt7r

**Comment by jzaefferer** [comment]
Yes, prepublishing is fine. How about `beta` for the tag?
