### ISSUE TITLE
Hook does not display errors

### ISSUE THREAD

**Issue by ZwoRmi** [jzaefferer/commitplease#89]
I think I've misunderstand something.
According to the doc, I've installed your package using `npm install commitplease --save-dev`. That's working, I can see the hook `.git/hooks/commit-msg`. 
The hook is trigerred when I run `git commit -m 'my message'`. The main function of your `index.js` is called **but** the `runValidate()` function is not called.

Do I need another option for this `runValidate` function to be called?

**Comment by all3fox** [comment]
Hello, @ZwoRmi 

Is the root of your git repository (I mean the `.git` folder) in the same folder as your `node_modules`? If yes, does it contain more files than just `.git/hooks/commit-msg`?

What you are supposed to do is this:

```
mkdir my_project && cd my_project
git init
npm init --yes
npm install commitplease --save-dev
```

**Comment by ZwoRmi** [comment]
If I comment those 2 lines in `index.js`, everything works fine :

```
...
var options = getOptions()
var message = path.join('.git', 'COMMIT_EDITMSG')

//--- if (argv[0] === message) { ---
  runValidate(fs.readFileSync(message, 'utf8').toString(), options)

  process.exit(0)
//--- } ---

var committish = 'HEAD'
if (argv.length !== 0) {
  committish = argv[0]
}
...
```

But I'm pretty sure I'm breaking other features

**Comment by ZwoRmi** [comment]
@all3fox Yes my `.git` folder is in the same folder as my `node_modules`.
My `.git/hooks/` folder contains git default `.sample`

**Comment by all3fox** [comment]
What are your `node --version`, `git --version`, your OS?

Did you setup anything commitplease-related in your `package.json`?

**Comment by ZwoRmi** [comment]
```
>node --version
v4.6.0
```

```
>git --version
git version 2.9.0.windows.1
```

OS -> Windows 10

In my `package.json` I've added thedefault  angular config from your README.md :
```
"commitplease": {
    "style": "angular",
    "types": [
      "feat", "fix", "docs", "style", "refactor", "perf", "test", "chore"
    ],
    "scope": "\\S+.*"
  }
```

**Comment by ZwoRmi** [comment]
Oh.. windows windows windows...

```
argv[0] :.git/COMMIT_EDITMSG
message :.git\COMMIT_EDITMSG
```

**Comment by all3fox** [comment]
Strange, so `path.join` chooses the backward slash `\` because it is on windows, yet `argv[0]` gets it with a forward slash `/`. Are you by any chance on MinGW or anything like that?

**Comment by ZwoRmi** [comment]
Yes, I'm not sure but I think I'm using MSysgit (installed when I installed git on windows)

**Comment by all3fox** [comment]
Ok, I have read the readme of MSysgit: https://github.com/msysgit/msysgit/

It seems to pretend as if it were a Linux (gives you bash, gcc and all) and provides a Linux-like `argv[0]`. And you probably installed node with the "node for windows" option [from the node website](https://nodejs.org/en/download/), so the `path` knows that you are on windows. Hence the confusion.

Unfortunately, I have no experience developing/setting up javascript on Windows. How about you install a [git for windows](https://git-scm.com/download/win) instead of MSysgit? Maybe that will not pretend to be a Linux-like environment. No guarantees though.

**Comment by ZwoRmi** [comment]
I will try this. Thanks for all your help since that's clearly not your package but my configuration which causes this issue. 

Hope this great package will continue to evolve.
