### ISSUE TITLE
Using a word containing a keyword breaks the validation

### ISSUE THREAD

**Issue by mgol** [jzaefferer/commitplease#91]
I discovered that using the word "reformat" in the commit description breaks the validation, saying there is an incorrect ticket reference. I assume this is because of the "ref" prefix in the word; changing it to "re-format" fixes the check.

**Comment by all3fox** [comment]
Hello @mgol, I have tried to reproduce it with `2.7.6` by placing `reformat` into the first line, as well as at the beginning and the body of the commit message (4 variations in total). It triggered no problems for me.

Could you tell me your commitplease version as well as any settings you set in `package.json`? Could you also share the commit message?

Finally, I have done a `grep "ref" -R --exclude-dir=node_modules --exclude-dir=\.git` and it looks like the candidate offenders are:

1. `(refs?)` as part of the `markerPattern` for jQuery
2. `refactor`, an Angular keyword

**Comment by mgol** [comment]
I'm sorry, I haven't noticed we're using 2.6.1 in jQuery Core currently; that might be causing issues.

**Comment by all3fox** [comment]
I confirm that `2.6.1` is causing the issue, currently working on updating to `2.7.6` for jQuery Core

**Comment by mgol** [comment]
I'll close the issue since there is no problem in current commitplease. Thanks for confirming the situation!
